### ISSUE TITLE
Potentially overly strict seismic4d filter

### ISSUE THREAD

**Issue by SteffenEq** [equinor/fmu-sumo#348]
Hi,

Currently the seismic4d filter requires `base` and `monitor` keywords:
https://github.com/equinor/fmu-sumo/blob/e935ad1c85ff7ebcdb9ed6c7f22737a8a4f27f89/src/fmu/sumo/explorer/Filters.py#L2-L7

However, some seismic surfaces are defined by only having time *values*, e.g.
```yaml
  time:
    t0:
      value: "2019-10-01T00:00:00"
    t1:
      value: "2020-10-01T00:00:00"
```

which will cause `sumo_explorer.cases.filter(field=<field_name>, has=Filters.seismic4d)` to filter out these.

- Is this intentional? 
- Is the seismic4d perhaps overly strict? 
- Is t0 always base and t1 always monitor?
- Is t0 always before t1?
- Is it a metadata issue that these surfaces have t0 and t1 defined but with missing base/monitor?

Thanks!
